# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_AMBARELLA_CV25) += cv25_oclea_usom.dtb
dtb-$(CONFIG_ARCH_AMBARELLA_CV25) += cv25_oclea_usom_breakout_evk.dtb
dtb-$(CONFIG_ARCH_AMBARELLA_CV25) += cv25_oclea_usom_zeus.dtb
dtb-$(CONFIG_ARCH_AMBARELLA_CV25) += cv25_oclea_usom_evk2.dtb

